service: redirect

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    # Unlabelled
    -  Effect: Allow
       Action:
         - s3:PutObject
       Resource:
         - "arn:aws:s3:::redirect-stored-replies/*"
    -  Effect: Allow
       Action:
         - s3:GetObject
       Resource:
         - "arn:aws:s3:::redirect-stored-replies/*"
    -  Effect: Allow
       Action:
         - s3:DeleteObject
       Resource:
         - "arn:aws:s3:::redirect-stored-replies/*"
    -  Effect: Allow
       Action:
         - s3:GetObjectAcl
       Resource:
         - "arn:aws:s3:::redirect-stored-replies/*"
    -  Effect: Allow
       Action:
         - s3:ListBucket
       Resource:
         - "arn:aws:s3:::redirect-stored-replies"

functions:
  get:
    handler: src/get.main
    events:
      - http:
          path: /{kind}
          method: get
          cors: true
          authorizer: aws_iam
# Create our resources with separate CloudFormation templates
resources:
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
